import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:brightmath/core/database/question_bank_generator.dart';
import 'package:brightmath/features/chapters/domain/chapter_models.dart';

const _databaseVersion = 9;
const _questionCountPerChapter = 500;
const _maxGenerationAttemptsPerChapter = 20000;
const _root = 'assets/database';
const _questionsDir = '$_root/init/questions';

void main() async {
  final generator = QuestionBankGenerator();
  await Directory(_questionsDir).create(recursive: true);

  final questionScripts = <String>[];
  await _writeChaptersScript();
  for (final chapter in chapterDefinitions) {
    final filename = _chapterQuestionFilename(chapter);
    final path = '$_questionsDir/$filename';
    final questions = _generateUniqueQuestions(generator, chapter)
      ..sort(_compareQuestionsByArguments);
    await File(path).writeAsString(_questionsSql(chapter, questions));
    questionScripts.add(path);
  }

  final manifest = const JsonEncoder.withIndent('  ').convert({
    'databaseVersion': _databaseVersion,
    'createScripts': ['$_root/migrations/001_initial_schema.sql'],
    'initialContentScripts': ['$_root/init/chapters.sql', ...questionScripts],
    'upgrades': [
      {
        'version': 5,
        'scripts': ['$_root/migrations/005_static_question_bank.sql'],
      },
      {
        'version': 6,
        'scripts': ['$_root/migrations/006_refresh_option_pools.sql'],
      },
      {
        'version': 7,
        'scripts': ['$_root/migrations/007_refresh_easy_non_negative.sql'],
      },
      {
        'version': 8,
        'scripts': ['$_root/migrations/008_refresh_zero_free_questions.sql'],
      },
      {
        'version': 9,
        'scripts': [
          '$_root/migrations/009_refresh_addition_positive_options.sql',
        ],
      },
    ],
  });
  await File('$_root/manifest.json').writeAsString('$manifest\n');
}

Future<void> _writeChaptersScript() async {
  final buffer = StringBuffer()
    ..writeln('-- Generated by tool/generate_database_sql.dart.')
    ..writeln('INSERT OR IGNORE INTO chapters (')
    ..writeln('  id,')
    ..writeln('  order_index,')
    ..writeln('  topic_code,')
    ..writeln('  difficulty,')
    ..writeln('  title,')
    ..writeln('  description,')
    ..writeln('  kind,')
    ..writeln('  quiz_mode')
    ..writeln(') VALUES');

  for (var i = 0; i < chapterDefinitions.length; i++) {
    final chapter = chapterDefinitions[i];
    final suffix = i == chapterDefinitions.length - 1 ? ';' : ',';
    buffer.writeln(
      '  (${chapter.id}, ${chapter.orderIndex}, '
      '${_sqlString(chapter.topicCode)}, '
      '${_sqlString(chapter.difficulty.name)}, '
      '${_sqlString(chapter.titleKey)}, '
      '${_sqlString(chapter.descriptionKey)}, '
      '${_sqlString(chapter.kind.name)}, '
      '${_sqlString(chapter.quizMode.name)})$suffix',
    );
  }

  buffer.writeln();
  for (final chapter in chapterDefinitions) {
    buffer
      ..writeln('UPDATE chapters')
      ..writeln('SET')
      ..writeln('  order_index = ${chapter.orderIndex},')
      ..writeln('  topic_code = ${_sqlString(chapter.topicCode)},')
      ..writeln('  difficulty = ${_sqlString(chapter.difficulty.name)},')
      ..writeln('  title = ${_sqlString(chapter.titleKey)},')
      ..writeln('  description = ${_sqlString(chapter.descriptionKey)},')
      ..writeln('  kind = ${_sqlString(chapter.kind.name)},')
      ..writeln('  quiz_mode = ${_sqlString(chapter.quizMode.name)}')
      ..writeln('WHERE id = ${chapter.id};')
      ..writeln();
  }

  await Directory('$_root/init').create(recursive: true);
  await File('$_root/init/chapters.sql').writeAsString(buffer.toString());
}

List<GeneratedQuestion> _generateUniqueQuestions(
  QuestionBankGenerator generator,
  ChapterDefinition chapter,
) {
  final questions = <GeneratedQuestion>[];
  final signatures = <String>{};
  var seedOffset = 0;
  while (questions.length < _questionCountPerChapter &&
      seedOffset < _maxGenerationAttemptsPerChapter) {
    final rng = Random(chapter.id * 5000 + seedOffset * 11);
    final question = generator.generateQuestion(chapter, rng);
    seedOffset++;

    if (generator.isZeroZeroQuestion(
      question.prompt,
      question.rightExpression,
    )) {
      continue;
    }
    if (_shouldSkipQuestion(chapter, question)) {
      continue;
    }

    final signature = _questionIdentity(question);
    if (signatures.add(signature)) {
      questions.add(question);
    }
  }
  return questions;
}

String _questionIdentity(GeneratedQuestion question) {
  return [question.prompt, question.rightExpression ?? ''].join('\u0001');
}

bool _shouldSkipQuestion(
  ChapterDefinition chapter,
  GeneratedQuestion question,
) {
  if (chapter.difficulty == ChapterDifficulty.easy &&
      _hasNegativeNumber(question.correctAnswer)) {
    return true;
  }
  return _hasZeroQuestionArgument(question);
}

bool _hasZeroQuestionArgument(GeneratedQuestion question) {
  return _argumentValues(question).any((value) => value == 0);
}

int _compareQuestionsByArguments(
  GeneratedQuestion left,
  GeneratedQuestion right,
) {
  final argumentComparison = _compareNumberLists(
    _argumentValues(left),
    _argumentValues(right),
  );
  if (argumentComparison != 0) {
    return argumentComparison;
  }

  return _compareStrings([
    (left.prompt, right.prompt),
    (left.rightExpression ?? '', right.rightExpression ?? ''),
    (left.correctAnswer, right.correctAnswer),
    (left.options.join('|'), right.options.join('|')),
  ]);
}

List<num> _argumentValues(GeneratedQuestion question) {
  return _extractNumbers(
    [
      question.prompt,
      if (question.rightExpression != null) question.rightExpression!,
    ].join(' '),
  );
}

List<num> _extractNumbers(String expression) {
  return RegExp(r'-?\d+(?:\.\d+)?')
      .allMatches(expression)
      .map((match) {
        final raw = match.group(0)!;
        return raw.contains('.') ? double.parse(raw) : int.parse(raw);
      })
      .toList(growable: false);
}

int _compareNumberLists(List<num> left, List<num> right) {
  final limit = min(left.length, right.length);
  for (var i = 0; i < limit; i++) {
    final comparison = left[i].compareTo(right[i]);
    if (comparison != 0) {
      return comparison;
    }
  }
  return left.length.compareTo(right.length);
}

int _compareStrings(List<(String, String)> pairs) {
  for (final (left, right) in pairs) {
    final comparison = left.compareTo(right);
    if (comparison != 0) {
      return comparison;
    }
  }
  return 0;
}

String _questionsSql(
  ChapterDefinition chapter,
  List<GeneratedQuestion> questions,
) {
  final buffer = StringBuffer()
    ..writeln('-- Generated by tool/generate_database_sql.dart.')
    ..writeln(
      '-- Chapter ${chapter.id}: ${chapter.topicCode} '
      '${chapter.difficulty.name}.',
    )
    ..writeln('INSERT OR REPLACE INTO questions (')
    ..writeln('  chapter_id,')
    ..writeln('  question_key,')
    ..writeln('  prompt,')
    ..writeln('  right_expr,')
    ..writeln('  correct_answer,')
    ..writeln('  options,')
    ..writeln('  content_version')
    ..writeln(') VALUES');

  for (var i = 0; i < questions.length; i++) {
    final question = questions[i];
    final options = _optionsForChapter(chapter, question);
    final suffix = i == questions.length - 1 ? ';' : ',';
    buffer.writeln(
      '  (${chapter.id}, '
      '${_sqlString(_questionKey(chapter.id, i))}, '
      '${_sqlString(question.prompt)}, '
      '${_nullableSqlString(question.rightExpression)}, '
      '${_sqlString(question.correctAnswer)}, '
      '${_sqlString(options.join('|'))}, '
      '1)$suffix',
    );
  }
  return buffer.toString();
}

List<String> _optionsForChapter(
  ChapterDefinition chapter,
  GeneratedQuestion question,
) {
  if (chapter.kind == ChapterKind.additionWhole &&
      chapter.difficulty != ChapterDifficulty.hard) {
    return question.options
        .where((option) => !_isZeroOrNegativeNumber(option))
        .toList(growable: false);
  }
  if (chapter.difficulty != ChapterDifficulty.easy) {
    return question.options;
  }
  return question.options
      .where((option) => !_hasNegativeNumber(option))
      .toList(growable: false);
}

bool _hasNegativeNumber(String value) {
  return RegExp(r'(^|[^\d])-').hasMatch(value);
}

bool _isZeroOrNegativeNumber(String value) {
  final parsed = num.tryParse(value);
  return parsed != null && parsed <= 0;
}

String _chapterQuestionFilename(ChapterDefinition chapter) {
  final id = chapter.id.toString().padLeft(3, '0');
  return '${id}_${chapter.topicCode}_${chapter.difficulty.name}.sql';
}

String _questionKey(int chapterId, int zeroBasedIndex) {
  return '${chapterId.toString().padLeft(3, '0')}-'
      '${(zeroBasedIndex + 1).toString().padLeft(4, '0')}';
}

String _nullableSqlString(String? value) {
  return value == null ? 'NULL' : _sqlString(value);
}

String _sqlString(String value) {
  return "'${value.replaceAll("'", "''")}'";
}
