-- Generated by tool/generate_database_sql.dart.
INSERT OR IGNORE INTO chapters (
  id,
  order_index,
  topic_code,
  difficulty,
  title,
  description,
  kind,
  quiz_mode
) VALUES
  (1, 1, 'add_whole', 'easy', 'Addition', 'Train whole-number addition speed and accuracy.', 'additionWhole', 'multipleChoice'),
  (2, 2, 'add_whole', 'medium', 'Addition', 'Train whole-number addition speed and accuracy.', 'additionWhole', 'multipleChoice'),
  (3, 3, 'add_whole', 'hard', 'Addition', 'Train whole-number addition speed and accuracy.', 'additionWhole', 'multipleChoice'),
  (4, 4, 'sub_whole', 'easy', 'Subtraction', 'Build whole-number subtraction confidence.', 'subtractionWhole', 'multipleChoice'),
  (5, 5, 'sub_whole', 'medium', 'Subtraction', 'Build whole-number subtraction confidence.', 'subtractionWhole', 'multipleChoice'),
  (6, 6, 'sub_whole', 'hard', 'Subtraction', 'Build whole-number subtraction confidence.', 'subtractionWhole', 'multipleChoice'),
  (7, 7, 'mul_whole', 'easy', 'Multiplication', 'Practice multiplication fluency.', 'multiplicationWhole', 'multipleChoice'),
  (8, 8, 'mul_whole', 'medium', 'Multiplication', 'Practice multiplication fluency.', 'multiplicationWhole', 'multipleChoice'),
  (9, 9, 'mul_whole', 'hard', 'Multiplication', 'Practice multiplication fluency.', 'multiplicationWhole', 'multipleChoice'),
  (10, 10, 'div_whole', 'easy', 'Division', 'Solve whole-number division questions.', 'divisionWhole', 'multipleChoice'),
  (11, 11, 'div_whole', 'medium', 'Division', 'Solve whole-number division questions.', 'divisionWhole', 'multipleChoice'),
  (12, 12, 'div_whole', 'hard', 'Division', 'Solve whole-number division questions.', 'divisionWhole', 'multipleChoice'),
  (13, 13, 'compare_whole_frac', 'easy', 'Compare Numbers', 'Choose >, <, or = for whole/fraction values.', 'compareWholeFractions', 'comparison'),
  (14, 14, 'compare_whole_frac', 'medium', 'Compare Numbers', 'Choose >, <, or = for whole/fraction values.', 'compareWholeFractions', 'comparison'),
  (15, 15, 'compare_whole_frac', 'hard', 'Compare Numbers', 'Choose >, <, or = for whole/fraction values.', 'compareWholeFractions', 'comparison'),
  (16, 16, 'add_frac', 'easy', 'Fraction Addition', 'Add fractions with different denominators.', 'additionFractions', 'multipleChoice'),
  (17, 17, 'add_frac', 'medium', 'Fraction Addition', 'Add fractions with different denominators.', 'additionFractions', 'multipleChoice'),
  (18, 18, 'add_frac', 'hard', 'Fraction Addition', 'Add fractions with different denominators.', 'additionFractions', 'multipleChoice'),
  (19, 19, 'sub_frac', 'easy', 'Fraction Subtraction', 'Subtract fractions accurately.', 'subtractionFractions', 'multipleChoice'),
  (20, 20, 'sub_frac', 'medium', 'Fraction Subtraction', 'Subtract fractions accurately.', 'subtractionFractions', 'multipleChoice'),
  (21, 21, 'sub_frac', 'hard', 'Fraction Subtraction', 'Subtract fractions accurately.', 'subtractionFractions', 'multipleChoice'),
  (22, 22, 'mul_frac', 'easy', 'Fraction Multiplication', 'Multiply fractions and simplify.', 'multiplicationFractions', 'multipleChoice'),
  (23, 23, 'mul_frac', 'medium', 'Fraction Multiplication', 'Multiply fractions and simplify.', 'multiplicationFractions', 'multipleChoice'),
  (24, 24, 'mul_frac', 'hard', 'Fraction Multiplication', 'Multiply fractions and simplify.', 'multiplicationFractions', 'multipleChoice'),
  (25, 25, 'frac_convert', 'easy', 'Fraction Convert/Compare', 'Convert and compare mixed/improper fractions.', 'fractionConvertCompare', 'multipleChoice'),
  (26, 26, 'frac_convert', 'medium', 'Fraction Convert/Compare', 'Convert and compare mixed/improper fractions.', 'fractionConvertCompare', 'multipleChoice'),
  (27, 27, 'frac_convert', 'hard', 'Fraction Convert/Compare', 'Convert and compare mixed/improper fractions.', 'fractionConvertCompare', 'multipleChoice'),
  (28, 28, 'frac_simplify', 'easy', 'Fraction Simplification', 'Reduce fractions to lowest terms.', 'fractionSimplify', 'multipleChoice'),
  (29, 29, 'frac_simplify', 'medium', 'Fraction Simplification', 'Reduce fractions to lowest terms.', 'fractionSimplify', 'multipleChoice'),
  (30, 30, 'frac_simplify', 'hard', 'Fraction Simplification', 'Reduce fractions to lowest terms.', 'fractionSimplify', 'multipleChoice'),
  (31, 31, 'compare_ops', 'easy', 'Compare Operations', 'Compare operation-based expressions.', 'compareOperations', 'comparison'),
  (32, 32, 'compare_ops', 'medium', 'Compare Operations', 'Compare operation-based expressions.', 'compareOperations', 'comparison'),
  (33, 33, 'compare_ops', 'hard', 'Compare Operations', 'Compare operation-based expressions.', 'compareOperations', 'comparison'),
  (34, 34, 'percent', 'easy', 'Percentages', 'Compute percentage expressions.', 'percentage', 'multipleChoice'),
  (35, 35, 'percent', 'medium', 'Percentages', 'Compute percentage expressions.', 'percentage', 'multipleChoice'),
  (36, 36, 'percent', 'hard', 'Percentages', 'Compute percentage expressions.', 'percentage', 'multipleChoice'),
  (37, 37, 'power', 'easy', 'Powers', 'Evaluate powers of numbers.', 'power', 'multipleChoice'),
  (38, 38, 'power', 'medium', 'Powers', 'Evaluate powers of numbers.', 'power', 'multipleChoice'),
  (39, 39, 'power', 'hard', 'Powers', 'Evaluate powers of numbers.', 'power', 'multipleChoice'),
  (40, 40, 'sqrt', 'easy', 'Square Roots', 'Solve square-root questions.', 'squareRoot', 'multipleChoice'),
  (41, 41, 'sqrt', 'medium', 'Square Roots', 'Solve square-root questions.', 'squareRoot', 'multipleChoice'),
  (42, 42, 'sqrt', 'hard', 'Square Roots', 'Solve square-root questions.', 'squareRoot', 'multipleChoice'),
  (43, 43, 'paren', 'easy', 'Parenthesis Basics', 'Solve expressions with parentheses.', 'parenthesis', 'multipleChoice'),
  (44, 44, 'paren', 'medium', 'Parenthesis Basics', 'Solve expressions with parentheses.', 'parenthesis', 'multipleChoice'),
  (45, 45, 'paren', 'hard', 'Parenthesis Basics', 'Solve expressions with parentheses.', 'parenthesis', 'multipleChoice'),
  (46, 46, 'nested_paren', 'easy', 'Nested Parentheses', 'Use order of operations in nested forms.', 'nestedParenthesis', 'multipleChoice'),
  (47, 47, 'nested_paren', 'medium', 'Nested Parentheses', 'Use order of operations in nested forms.', 'nestedParenthesis', 'multipleChoice'),
  (48, 48, 'nested_paren', 'hard', 'Nested Parentheses', 'Use order of operations in nested forms.', 'nestedParenthesis', 'multipleChoice'),
  (49, 49, 'compare_paren', 'easy', 'Compare Parentheses', 'Compare parenthesized expressions.', 'compareParenthesis', 'comparison'),
  (50, 50, 'compare_paren', 'medium', 'Compare Parentheses', 'Compare parenthesized expressions.', 'compareParenthesis', 'comparison'),
  (51, 51, 'compare_paren', 'hard', 'Compare Parentheses', 'Compare parenthesized expressions.', 'compareParenthesis', 'comparison'),
  (52, 52, 'mixed_1', 'easy', 'Mixed I', 'Mixed questions from introduced topics.', 'mixedBasic', 'multipleChoice'),
  (53, 53, 'mixed_1', 'medium', 'Mixed I', 'Mixed questions from introduced topics.', 'mixedBasic', 'multipleChoice'),
  (54, 54, 'mixed_1', 'hard', 'Mixed I', 'Mixed questions from introduced topics.', 'mixedBasic', 'multipleChoice'),
  (55, 55, 'mixed_2', 'easy', 'Mixed II', 'Harder mixed-topic questions.', 'mixedAdvanced', 'multipleChoice'),
  (56, 56, 'mixed_2', 'medium', 'Mixed II', 'Harder mixed-topic questions.', 'mixedAdvanced', 'multipleChoice'),
  (57, 57, 'mixed_2', 'hard', 'Mixed II', 'Harder mixed-topic questions.', 'mixedAdvanced', 'multipleChoice'),
  (58, 58, 'mixed_final', 'easy', 'Mixed Final', 'Final mixed challenge chapter.', 'mixedFinal', 'multipleChoice'),
  (59, 59, 'mixed_final', 'medium', 'Mixed Final', 'Final mixed challenge chapter.', 'mixedFinal', 'multipleChoice'),
  (60, 60, 'mixed_final', 'hard', 'Mixed Final', 'Final mixed challenge chapter.', 'mixedFinal', 'multipleChoice');

UPDATE chapters
SET
  order_index = 1,
  topic_code = 'add_whole',
  difficulty = 'easy',
  title = 'Addition',
  description = 'Train whole-number addition speed and accuracy.',
  kind = 'additionWhole',
  quiz_mode = 'multipleChoice'
WHERE id = 1;

UPDATE chapters
SET
  order_index = 2,
  topic_code = 'add_whole',
  difficulty = 'medium',
  title = 'Addition',
  description = 'Train whole-number addition speed and accuracy.',
  kind = 'additionWhole',
  quiz_mode = 'multipleChoice'
WHERE id = 2;

UPDATE chapters
SET
  order_index = 3,
  topic_code = 'add_whole',
  difficulty = 'hard',
  title = 'Addition',
  description = 'Train whole-number addition speed and accuracy.',
  kind = 'additionWhole',
  quiz_mode = 'multipleChoice'
WHERE id = 3;

UPDATE chapters
SET
  order_index = 4,
  topic_code = 'sub_whole',
  difficulty = 'easy',
  title = 'Subtraction',
  description = 'Build whole-number subtraction confidence.',
  kind = 'subtractionWhole',
  quiz_mode = 'multipleChoice'
WHERE id = 4;

UPDATE chapters
SET
  order_index = 5,
  topic_code = 'sub_whole',
  difficulty = 'medium',
  title = 'Subtraction',
  description = 'Build whole-number subtraction confidence.',
  kind = 'subtractionWhole',
  quiz_mode = 'multipleChoice'
WHERE id = 5;

UPDATE chapters
SET
  order_index = 6,
  topic_code = 'sub_whole',
  difficulty = 'hard',
  title = 'Subtraction',
  description = 'Build whole-number subtraction confidence.',
  kind = 'subtractionWhole',
  quiz_mode = 'multipleChoice'
WHERE id = 6;

UPDATE chapters
SET
  order_index = 7,
  topic_code = 'mul_whole',
  difficulty = 'easy',
  title = 'Multiplication',
  description = 'Practice multiplication fluency.',
  kind = 'multiplicationWhole',
  quiz_mode = 'multipleChoice'
WHERE id = 7;

UPDATE chapters
SET
  order_index = 8,
  topic_code = 'mul_whole',
  difficulty = 'medium',
  title = 'Multiplication',
  description = 'Practice multiplication fluency.',
  kind = 'multiplicationWhole',
  quiz_mode = 'multipleChoice'
WHERE id = 8;

UPDATE chapters
SET
  order_index = 9,
  topic_code = 'mul_whole',
  difficulty = 'hard',
  title = 'Multiplication',
  description = 'Practice multiplication fluency.',
  kind = 'multiplicationWhole',
  quiz_mode = 'multipleChoice'
WHERE id = 9;

UPDATE chapters
SET
  order_index = 10,
  topic_code = 'div_whole',
  difficulty = 'easy',
  title = 'Division',
  description = 'Solve whole-number division questions.',
  kind = 'divisionWhole',
  quiz_mode = 'multipleChoice'
WHERE id = 10;

UPDATE chapters
SET
  order_index = 11,
  topic_code = 'div_whole',
  difficulty = 'medium',
  title = 'Division',
  description = 'Solve whole-number division questions.',
  kind = 'divisionWhole',
  quiz_mode = 'multipleChoice'
WHERE id = 11;

UPDATE chapters
SET
  order_index = 12,
  topic_code = 'div_whole',
  difficulty = 'hard',
  title = 'Division',
  description = 'Solve whole-number division questions.',
  kind = 'divisionWhole',
  quiz_mode = 'multipleChoice'
WHERE id = 12;

UPDATE chapters
SET
  order_index = 13,
  topic_code = 'compare_whole_frac',
  difficulty = 'easy',
  title = 'Compare Numbers',
  description = 'Choose >, <, or = for whole/fraction values.',
  kind = 'compareWholeFractions',
  quiz_mode = 'comparison'
WHERE id = 13;

UPDATE chapters
SET
  order_index = 14,
  topic_code = 'compare_whole_frac',
  difficulty = 'medium',
  title = 'Compare Numbers',
  description = 'Choose >, <, or = for whole/fraction values.',
  kind = 'compareWholeFractions',
  quiz_mode = 'comparison'
WHERE id = 14;

UPDATE chapters
SET
  order_index = 15,
  topic_code = 'compare_whole_frac',
  difficulty = 'hard',
  title = 'Compare Numbers',
  description = 'Choose >, <, or = for whole/fraction values.',
  kind = 'compareWholeFractions',
  quiz_mode = 'comparison'
WHERE id = 15;

UPDATE chapters
SET
  order_index = 16,
  topic_code = 'add_frac',
  difficulty = 'easy',
  title = 'Fraction Addition',
  description = 'Add fractions with different denominators.',
  kind = 'additionFractions',
  quiz_mode = 'multipleChoice'
WHERE id = 16;

UPDATE chapters
SET
  order_index = 17,
  topic_code = 'add_frac',
  difficulty = 'medium',
  title = 'Fraction Addition',
  description = 'Add fractions with different denominators.',
  kind = 'additionFractions',
  quiz_mode = 'multipleChoice'
WHERE id = 17;

UPDATE chapters
SET
  order_index = 18,
  topic_code = 'add_frac',
  difficulty = 'hard',
  title = 'Fraction Addition',
  description = 'Add fractions with different denominators.',
  kind = 'additionFractions',
  quiz_mode = 'multipleChoice'
WHERE id = 18;

UPDATE chapters
SET
  order_index = 19,
  topic_code = 'sub_frac',
  difficulty = 'easy',
  title = 'Fraction Subtraction',
  description = 'Subtract fractions accurately.',
  kind = 'subtractionFractions',
  quiz_mode = 'multipleChoice'
WHERE id = 19;

UPDATE chapters
SET
  order_index = 20,
  topic_code = 'sub_frac',
  difficulty = 'medium',
  title = 'Fraction Subtraction',
  description = 'Subtract fractions accurately.',
  kind = 'subtractionFractions',
  quiz_mode = 'multipleChoice'
WHERE id = 20;

UPDATE chapters
SET
  order_index = 21,
  topic_code = 'sub_frac',
  difficulty = 'hard',
  title = 'Fraction Subtraction',
  description = 'Subtract fractions accurately.',
  kind = 'subtractionFractions',
  quiz_mode = 'multipleChoice'
WHERE id = 21;

UPDATE chapters
SET
  order_index = 22,
  topic_code = 'mul_frac',
  difficulty = 'easy',
  title = 'Fraction Multiplication',
  description = 'Multiply fractions and simplify.',
  kind = 'multiplicationFractions',
  quiz_mode = 'multipleChoice'
WHERE id = 22;

UPDATE chapters
SET
  order_index = 23,
  topic_code = 'mul_frac',
  difficulty = 'medium',
  title = 'Fraction Multiplication',
  description = 'Multiply fractions and simplify.',
  kind = 'multiplicationFractions',
  quiz_mode = 'multipleChoice'
WHERE id = 23;

UPDATE chapters
SET
  order_index = 24,
  topic_code = 'mul_frac',
  difficulty = 'hard',
  title = 'Fraction Multiplication',
  description = 'Multiply fractions and simplify.',
  kind = 'multiplicationFractions',
  quiz_mode = 'multipleChoice'
WHERE id = 24;

UPDATE chapters
SET
  order_index = 25,
  topic_code = 'frac_convert',
  difficulty = 'easy',
  title = 'Fraction Convert/Compare',
  description = 'Convert and compare mixed/improper fractions.',
  kind = 'fractionConvertCompare',
  quiz_mode = 'multipleChoice'
WHERE id = 25;

UPDATE chapters
SET
  order_index = 26,
  topic_code = 'frac_convert',
  difficulty = 'medium',
  title = 'Fraction Convert/Compare',
  description = 'Convert and compare mixed/improper fractions.',
  kind = 'fractionConvertCompare',
  quiz_mode = 'multipleChoice'
WHERE id = 26;

UPDATE chapters
SET
  order_index = 27,
  topic_code = 'frac_convert',
  difficulty = 'hard',
  title = 'Fraction Convert/Compare',
  description = 'Convert and compare mixed/improper fractions.',
  kind = 'fractionConvertCompare',
  quiz_mode = 'multipleChoice'
WHERE id = 27;

UPDATE chapters
SET
  order_index = 28,
  topic_code = 'frac_simplify',
  difficulty = 'easy',
  title = 'Fraction Simplification',
  description = 'Reduce fractions to lowest terms.',
  kind = 'fractionSimplify',
  quiz_mode = 'multipleChoice'
WHERE id = 28;

UPDATE chapters
SET
  order_index = 29,
  topic_code = 'frac_simplify',
  difficulty = 'medium',
  title = 'Fraction Simplification',
  description = 'Reduce fractions to lowest terms.',
  kind = 'fractionSimplify',
  quiz_mode = 'multipleChoice'
WHERE id = 29;

UPDATE chapters
SET
  order_index = 30,
  topic_code = 'frac_simplify',
  difficulty = 'hard',
  title = 'Fraction Simplification',
  description = 'Reduce fractions to lowest terms.',
  kind = 'fractionSimplify',
  quiz_mode = 'multipleChoice'
WHERE id = 30;

UPDATE chapters
SET
  order_index = 31,
  topic_code = 'compare_ops',
  difficulty = 'easy',
  title = 'Compare Operations',
  description = 'Compare operation-based expressions.',
  kind = 'compareOperations',
  quiz_mode = 'comparison'
WHERE id = 31;

UPDATE chapters
SET
  order_index = 32,
  topic_code = 'compare_ops',
  difficulty = 'medium',
  title = 'Compare Operations',
  description = 'Compare operation-based expressions.',
  kind = 'compareOperations',
  quiz_mode = 'comparison'
WHERE id = 32;

UPDATE chapters
SET
  order_index = 33,
  topic_code = 'compare_ops',
  difficulty = 'hard',
  title = 'Compare Operations',
  description = 'Compare operation-based expressions.',
  kind = 'compareOperations',
  quiz_mode = 'comparison'
WHERE id = 33;

UPDATE chapters
SET
  order_index = 34,
  topic_code = 'percent',
  difficulty = 'easy',
  title = 'Percentages',
  description = 'Compute percentage expressions.',
  kind = 'percentage',
  quiz_mode = 'multipleChoice'
WHERE id = 34;

UPDATE chapters
SET
  order_index = 35,
  topic_code = 'percent',
  difficulty = 'medium',
  title = 'Percentages',
  description = 'Compute percentage expressions.',
  kind = 'percentage',
  quiz_mode = 'multipleChoice'
WHERE id = 35;

UPDATE chapters
SET
  order_index = 36,
  topic_code = 'percent',
  difficulty = 'hard',
  title = 'Percentages',
  description = 'Compute percentage expressions.',
  kind = 'percentage',
  quiz_mode = 'multipleChoice'
WHERE id = 36;

UPDATE chapters
SET
  order_index = 37,
  topic_code = 'power',
  difficulty = 'easy',
  title = 'Powers',
  description = 'Evaluate powers of numbers.',
  kind = 'power',
  quiz_mode = 'multipleChoice'
WHERE id = 37;

UPDATE chapters
SET
  order_index = 38,
  topic_code = 'power',
  difficulty = 'medium',
  title = 'Powers',
  description = 'Evaluate powers of numbers.',
  kind = 'power',
  quiz_mode = 'multipleChoice'
WHERE id = 38;

UPDATE chapters
SET
  order_index = 39,
  topic_code = 'power',
  difficulty = 'hard',
  title = 'Powers',
  description = 'Evaluate powers of numbers.',
  kind = 'power',
  quiz_mode = 'multipleChoice'
WHERE id = 39;

UPDATE chapters
SET
  order_index = 40,
  topic_code = 'sqrt',
  difficulty = 'easy',
  title = 'Square Roots',
  description = 'Solve square-root questions.',
  kind = 'squareRoot',
  quiz_mode = 'multipleChoice'
WHERE id = 40;

UPDATE chapters
SET
  order_index = 41,
  topic_code = 'sqrt',
  difficulty = 'medium',
  title = 'Square Roots',
  description = 'Solve square-root questions.',
  kind = 'squareRoot',
  quiz_mode = 'multipleChoice'
WHERE id = 41;

UPDATE chapters
SET
  order_index = 42,
  topic_code = 'sqrt',
  difficulty = 'hard',
  title = 'Square Roots',
  description = 'Solve square-root questions.',
  kind = 'squareRoot',
  quiz_mode = 'multipleChoice'
WHERE id = 42;

UPDATE chapters
SET
  order_index = 43,
  topic_code = 'paren',
  difficulty = 'easy',
  title = 'Parenthesis Basics',
  description = 'Solve expressions with parentheses.',
  kind = 'parenthesis',
  quiz_mode = 'multipleChoice'
WHERE id = 43;

UPDATE chapters
SET
  order_index = 44,
  topic_code = 'paren',
  difficulty = 'medium',
  title = 'Parenthesis Basics',
  description = 'Solve expressions with parentheses.',
  kind = 'parenthesis',
  quiz_mode = 'multipleChoice'
WHERE id = 44;

UPDATE chapters
SET
  order_index = 45,
  topic_code = 'paren',
  difficulty = 'hard',
  title = 'Parenthesis Basics',
  description = 'Solve expressions with parentheses.',
  kind = 'parenthesis',
  quiz_mode = 'multipleChoice'
WHERE id = 45;

UPDATE chapters
SET
  order_index = 46,
  topic_code = 'nested_paren',
  difficulty = 'easy',
  title = 'Nested Parentheses',
  description = 'Use order of operations in nested forms.',
  kind = 'nestedParenthesis',
  quiz_mode = 'multipleChoice'
WHERE id = 46;

UPDATE chapters
SET
  order_index = 47,
  topic_code = 'nested_paren',
  difficulty = 'medium',
  title = 'Nested Parentheses',
  description = 'Use order of operations in nested forms.',
  kind = 'nestedParenthesis',
  quiz_mode = 'multipleChoice'
WHERE id = 47;

UPDATE chapters
SET
  order_index = 48,
  topic_code = 'nested_paren',
  difficulty = 'hard',
  title = 'Nested Parentheses',
  description = 'Use order of operations in nested forms.',
  kind = 'nestedParenthesis',
  quiz_mode = 'multipleChoice'
WHERE id = 48;

UPDATE chapters
SET
  order_index = 49,
  topic_code = 'compare_paren',
  difficulty = 'easy',
  title = 'Compare Parentheses',
  description = 'Compare parenthesized expressions.',
  kind = 'compareParenthesis',
  quiz_mode = 'comparison'
WHERE id = 49;

UPDATE chapters
SET
  order_index = 50,
  topic_code = 'compare_paren',
  difficulty = 'medium',
  title = 'Compare Parentheses',
  description = 'Compare parenthesized expressions.',
  kind = 'compareParenthesis',
  quiz_mode = 'comparison'
WHERE id = 50;

UPDATE chapters
SET
  order_index = 51,
  topic_code = 'compare_paren',
  difficulty = 'hard',
  title = 'Compare Parentheses',
  description = 'Compare parenthesized expressions.',
  kind = 'compareParenthesis',
  quiz_mode = 'comparison'
WHERE id = 51;

UPDATE chapters
SET
  order_index = 52,
  topic_code = 'mixed_1',
  difficulty = 'easy',
  title = 'Mixed I',
  description = 'Mixed questions from introduced topics.',
  kind = 'mixedBasic',
  quiz_mode = 'multipleChoice'
WHERE id = 52;

UPDATE chapters
SET
  order_index = 53,
  topic_code = 'mixed_1',
  difficulty = 'medium',
  title = 'Mixed I',
  description = 'Mixed questions from introduced topics.',
  kind = 'mixedBasic',
  quiz_mode = 'multipleChoice'
WHERE id = 53;

UPDATE chapters
SET
  order_index = 54,
  topic_code = 'mixed_1',
  difficulty = 'hard',
  title = 'Mixed I',
  description = 'Mixed questions from introduced topics.',
  kind = 'mixedBasic',
  quiz_mode = 'multipleChoice'
WHERE id = 54;

UPDATE chapters
SET
  order_index = 55,
  topic_code = 'mixed_2',
  difficulty = 'easy',
  title = 'Mixed II',
  description = 'Harder mixed-topic questions.',
  kind = 'mixedAdvanced',
  quiz_mode = 'multipleChoice'
WHERE id = 55;

UPDATE chapters
SET
  order_index = 56,
  topic_code = 'mixed_2',
  difficulty = 'medium',
  title = 'Mixed II',
  description = 'Harder mixed-topic questions.',
  kind = 'mixedAdvanced',
  quiz_mode = 'multipleChoice'
WHERE id = 56;

UPDATE chapters
SET
  order_index = 57,
  topic_code = 'mixed_2',
  difficulty = 'hard',
  title = 'Mixed II',
  description = 'Harder mixed-topic questions.',
  kind = 'mixedAdvanced',
  quiz_mode = 'multipleChoice'
WHERE id = 57;

UPDATE chapters
SET
  order_index = 58,
  topic_code = 'mixed_final',
  difficulty = 'easy',
  title = 'Mixed Final',
  description = 'Final mixed challenge chapter.',
  kind = 'mixedFinal',
  quiz_mode = 'multipleChoice'
WHERE id = 58;

UPDATE chapters
SET
  order_index = 59,
  topic_code = 'mixed_final',
  difficulty = 'medium',
  title = 'Mixed Final',
  description = 'Final mixed challenge chapter.',
  kind = 'mixedFinal',
  quiz_mode = 'multipleChoice'
WHERE id = 59;

UPDATE chapters
SET
  order_index = 60,
  topic_code = 'mixed_final',
  difficulty = 'hard',
  title = 'Mixed Final',
  description = 'Final mixed challenge chapter.',
  kind = 'mixedFinal',
  quiz_mode = 'multipleChoice'
WHERE id = 60;

